language: csharp

sudo: false  # use the new container-based Travis infrastructure

install:
  - mkdir ~/.config/.mono/keypairs
  - chmod 700 ~/.config/.mono/keypairs
  - chmod 777 ./build.sh

script:
  - ./build.sh Default
